sudo: required
language: java
jdk: openjdk8
  
env:
  global: 
  - secure: "encrypted-heroku-api-key"
  - COMMIT=${TRAVIS_COMMIT::7}
  
      
before_install:
  - chmod +x mvnw
 
script: 
  - ./mvnw clean install -B
  
cache:
  directories:
    - '$HOME/.m2/repository'
  

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: app-clientes-service